### ISSUE TITLE
Add Hero images

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#168]
As a user I want to see different images, passing by  on the front page, lets add some new images or  animation.

imagen to improve. 
![image](https://user-images.githubusercontent.com/5632966/90790433-4a3a7080-e2c5-11ea-8a81-c37e3e9fb510.png)

Example of images than can use
<img width="963" alt="Captura de Pantalla 2022-07-04 a la(s) 22 49 49" src="https://user-images.githubusercontent.com/104119005/177424134-d5aff19b-c2e5-4768-bf98-a46ec19aca89.png">

<img width="1309" alt="Captura de Pantalla 2022-07-04 a la(s) 22 51 50" src="https://user-images.githubusercontent.com/104119005/177424189-d832cbea-7a4d-4c68-a24a-04c094c06c1a.png">

![Op1](https://user-images.githubusercontent.com/104119005/177424232-1e35d706-08ef-41b7-aa06-da0245334981.jpg)

![op-2](https://user-images.githubusercontent.com/104119005/177424270-3936436e-b274-459d-8f2d-da4f6b678f67.jpg)

![Op3](https://user-images.githubusercontent.com/104119005/177424301-29f3bb23-4290-4b54-903e-155f2fca2c92.jpg)

Accentance criteria 

- [ ] Changes old view of the front page
- [ ] Add  new imagen or animation

**Comment by Mike3563** [comment]
this task is complete
