### ISSUE TITLE
Useful Links Section

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#169]
Add a new page under community Section where useful links can be included / listed 

- [How to learn to develop on EOSIO](https://medium.com/@theblockstalk/learning-eosio-development-telos-eos-and-other-blockchains-94d384a8b09f)
- [EOSIO blockchain developers workshop, March 2020](https://www.youtube.com/playlist?list=PLbq67nzUl6Prlg2Su8Rkmh8exeAL5O5l7)
- [EOSIO customization and governance](https://www.youtube.com/watch?v=ITDFQESxglc&list=PLbq67nzUl6Prlg2Su8Rkmh8exeAL5O5l7&index=9)

**Comment by xavier506** [comment]
aun falta version en español

**Comment by Mike3563** [comment]
- [ ] add spanish vercion
