### ISSUE TITLE
Add coinbase Link

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#176]
EN Label:  `Learn how EOSIO works and you’ll earn EOS tokens.`
https://www.coinbase.com/earn/eos/ 

ES Label: `Aprenda como funciona EOSIO y gane tokens EOS .`
https://www.coinbase.com/es-LA/earn/eos/

**Comment by AngeloCG97** [comment]
@xavier506 en cual pagina se debe añadir el enlace?
