### ISSUE TITLE
Improve Social Media Guidelines

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#178]
https://guias.eoscostarica.io/docs/redes-sociales

-  list links to all our social media accounts
-  describe how we use each one 
- Ask our employees to follow us 

We appreciate it when members of are team are enthusiastic to share and participate on social media , and engage with the broader eosio community.

We ask our team members to make public that they work for eos costa rica on their linked in profiles and github profiles.

Be mindful of language and spelling when you post in channels related to the company

**Comment by ldrojas** [comment]
- General guidelines: be respectful, mind language, and keep it professional when representing the company or talking about related topics to blockchain/crypto. 
- LinkedIn: 
   - Create account and follow https://www.linkedin.com/company/eoscostarica/.
   - Use template provided by LD and add a description for interns. 
   - Reshare posts with community.
- Twitter: 
   - Follow https://twitter.com/EOSCostaRica if you have one.
   - Reshare posts.
- Github: 
   - Create account and follow https://github.com/eoscostarica (must be explained).
   - Review repositories and ask for permissions.
   - Edit profile to appear as collab for EOSCR.
- Telegram: 
   - Create account and follow https://t.me/eoscr.
   - Search for channels: https://t.me/blockchaincostarica, https://t.me/eosEs, https://t.me/evodex_io, https://t.me/latamlink.
- Nice to follow us: Facebook, Instagram, Medium, Youtube.

**Comment by ldrojas** [comment]
[Texto para Linkedin.pdf](https://github.com/eoscostarica/guide.eoscostarica.io/files/5798184/Texto.para.Linkedin.pdf)
