### ISSUE TITLE
SEO / 301 redirects

### ISSUE THREAD

**Issue by JustinCast** [eoscostarica/guide.eoscostarica.io#21]
We should eliminate learn.eoscostarica.io  and redirect to develop portal so we dont loose any SEO  Link Juice.

- Use 301 redirects

**Comment by xavier506** [comment]
@JustinCast @AngeloCG97 @JeanVegaD 

esto me parece que esta un poco largo : desarrolladores.eoscostarica.io  

para los dominios podriamos pensar en nombres nuevos , y hacer los 301 redirects
`developers.eoscostarica.io` & `learn.eoscostarica.io` -> `guide.eoscostarica.io`
`desarrolladores.eoscotarica.io` &  `learn.eoscostarica.io/es/` -> `guias.eoscostarica.io`


Que les parece?

**Comment by JustinCast** [comment]
@xavier506 those names make more sense

**Comment by JeanVegaD** [comment]
@xavier506 me parece bien realizar este cambio.
