### ISSUE TITLE
Search broken links, images and videos in repositories

### ISSUE THREAD

**Issue by AngeloCG97** [eoscostarica/guide.eoscostarica.io#221]
- [x] Developer Guidelines - eoscostarica.io
- [x] DevOps- https://github.com/edenia/openstack-docs
- [x] DevOps - https://github.com/edenia/openstack-docs/blob/master/Kubernetes.md
- [x] DevOps - What is a Container?
- [x] Open Source Projects - https://eos-foundation.eosio.cr - WARNING
- [x] Open Source Projects - https://notarize.eosio.cr/dashboard/notary
- [x] Backend Boilerplate - hasura
- [x] Node installation -  Example
- [x] Block Explorers - https://eospark.com/
- [x] Block Explorers - https://glass.cypherglass.com/map/main/top50
- [x] Block Explorers - https://monitor.telosfoundation.io/
- [x] EOS Podcast - EOS Radio
- [x] EOS Podcast - EOS Dublin
- [x] EOS Podcast - EOS Dapp Stars

**Comment by leisterfrancisco** [comment]
@AngeloCG97 I hope you are going well. In this issue description I wrote all the links that I found broken or with some error in the opening or referring moment, so, I would appreciate if you can instruct me to to know how to get the correct links or well if you can tell me who can I ask for that information.
