### ISSUE TITLE
Docker & Docker Compose Tutorial

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#224]
Describe docker docker compise and kubernetes

What is a container

**Comment by leisterfrancisco** [comment]
@xavier506 You here like a kind of introduction in brief information about Docker and Docker Compose and later a kind of installation, meaning tutorial, something like that?

I got some useful information from this [Learn Docker in 7 Easy Steps - Full Beginner's Tutorial](https://www.youtube.com/watch?v=gAkwW2tuIqE&t) and [Docker in 100 Seconds](https://www.youtube.com/watch?v=Gjnup-PuquQ), also from Wikipedia en Docker page

**Comment by leisterfrancisco** [comment]
@xavier506 @steph222 @Edgar097 I have created this [Doc](https://docs.google.com/document/d/1tv-Rby1EU7sgSNb0SlrR7rptzHz7uVLeYtrS2dvd08E/edit?usp=sharing), please take a look and if needed give me some recomendation

**Comment by leisterfrancisco** [comment]
I think I could add something like [this](https://fireship.io/lessons/docker-basics-tutorial-nodejs/)

**Comment by steph222** [comment]
> @xavier506 @steph222 @Edgar097 I have created this [Doc](https://docs.google.com/document/d/1tv-Rby1EU7sgSNb0SlrR7rptzHz7uVLeYtrS2dvd08E/edit?usp=sharing), please take a look and if needed give me some recomendation

Of course!!

**Comment by xavier506** [comment]
> I think I could add something like [this](https://fireship.io/lessons/docker-basics-tutorial-nodejs/)

I think this looks great!!

**Comment by Edgar097** [comment]
WIP 
Feedback please
@xavier506, @steph222 
---
id: docker-y-docker-compose
title: Docker
sidebar_label: Docker
---

## Docker Engine

Docker Engine es una tecnología de contenedorización de código abierto para crear y contener sus aplicaciones. Docker Engine actúa como una aplicación cliente-servidor con:

- Un servidor con un proceso de daemon dockerd de larga ejecución.
- API que especifican interfaces que los programas pueden usar para comunicarse e instruir al daemon Docker.
- Una ventana acoplable de cliente de interfaz de línea de comandos (CLI).

La CLI utiliza las API de Docker para controlar o interactuar con el daemon de Docker mediante secuencias de comandos o comandos directos de la CLI. Muchas otras aplicaciones de Docker utilizan la API y la CLI subyacentes. El daemon crea y administra objetos de Docker, como imágenes, contenedores, redes y volúmenes.

Para obtener más detalles, consulte [Arquitectura de Docker](https://docs.docker.com/get-started/overview/#docker-architecture).

[**Tutorial de Docker con Node.js**](https://fireship.io/lessons/docker-basics-tutorial-nodejs/)

### Archivo de Docker

Ejemplo de un archivo de Docker, es el *ADN* de la Docker Image.

```Dockerfile
FROM node:12

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV PORT=8080

EXPOSE 8080

CMD [ "npm", "start" ]
```

Se hace el *build* de la imagen de esta forma:

```shell
docker build -t fireship/demoapp:1.0 .
```

### Contenedor de Docker

Los contenedores son la solución al problema habitual, por ejemplo, de moverse entre entornos de desarrollo como puede ser una máquina local o en un entorno real de producción. Podemos probar de forma segura una aplicación sin preocuparnos de que nuestro código se comporte de forma distinta.

[**Documentación**](https://docs.docker.com/engine/reference/commandline/container/)

**Correr contenedor**  
Esto asigna el puerto local 5000 al puerto de la ventana acoplable 8080. Debería poder ver la aplicación en su sistema local en https://localhost:5000. Puede elegir el puerto que desee.

```shell
docker run -p 5000:8080 <image-id>
```

## Docker Compose

Compose es una herramienta para definir y ejecutar aplicaciones Docker de varios contenedores. Con Compose, se usa un archivo YAML para configurar los servicios de su aplicación. Luego, con un solo comando, crea e inicia todos los servicios desde su configuración.

Usar Compose es básicamente un proceso de tres pasos:

- Defina el entorno de su aplicación con un Dockerfile para que pueda reproducirse en cualquier lugar.
- Defina los servicios que componen su aplicación en docker-compose.yml para que puedan ejecutarse juntos en un entorno aislado.
- Ejecute toda su aplicación.

```shell
docker-compose up
```

Un docker-compose.yml se ve así:

```yml
version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
```

## Docker Windows

### WSL 2

Subsistema de Windows para Linux versión 2, es un sistema o máquina virtual de Linux que corre en Windows. Es recomendado utilizar este subsistema en conjunto con Docker.

- Vaya a su Panel de control.
- Vaya a Programas -> Programas y características.
- Luego, haz clic en Activar o desactivar las funciones de Windows.
- Busque la opción y haga clic en *Subsistema de Windows para Linux*, *Plataforma de máquina virtual* y *Plataforma de hipervisor de Windows* y luego presione Aceptar.
- Ahora necesita reiniciar su sistema operativo Windows.
- Finalmente, vaya a su Microsoft Store y busque el sistema operativo Linux que desee, le recomendamos que instale Ubuntu 18.04 LTS.

> [Más información](https://guias.eoscostarica.io/docs/aprender-eosio/componentes-eosio#instalaci%C3%B3n-en-windows)

#### Instalar de Forma Manual

[Instalar el WSL y Actualizarlo a WSL 2](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package)

1. Abrir PowerShell

```shell
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
```

2. Permitir Virtual Machine feature

```shell
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
```

3. Instalar el paquete de actulización de este [sitio](https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-4---download-the-linux-kernel-update-package) o [Paquete de Actualización](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi). Una vez instalado se debe actualizar el WSL 2 por defecto.

4. Hacer el WSL 2 por defecto.

```shell
wsl --set-default-version 2
```

<figure
class="video_container">
  <iframe 
  width="100%" height="315" src="https://www.youtube.com/embed/_fntjriRe48" frameborder="0" allowfullscreen="true"> 
  </iframe>
</figure>

### Instalar Docker Desktop

#### **Docker Desktop**

Docker Desktop es una aplicación fácil de instalar para su entorno Mac o Windows que le permite crear y compartir aplicaciones y microservicios en contenedores. Docker Desktop incluye Docker Engine, Docker CLI client, Docker Compose, Notary, Kubernetes y Credential Helper.
Docker Desktop funciona con su elección de herramientas de desarrollo e idiomas y le brinda acceso a una amplia biblioteca de imágenes y plantillas certificadas en Docker Hub. Esto permite a los equipos de desarrollo ampliar su entorno para construir rápidamente, integrarse continuamente y colaborar utilizando un repositorio seguro.
Algunas de las características clave de Docker Desktop incluyen:

- Capacidad para contener y compartir cualquier aplicación en cualquier plataforma en la nube, en múltiples lenguajes y marcos.
- Fácil instalación y configuración de un completo entorno de desarrollo Docker.
- Incluye la última versión de Kubernetes.
- Actualizaciones automáticas para mantenerte actualizado y seguro.
- En Windows, la capacidad de alternar entre entornos Linux y Windows Server para crear aplicaciones.
- Rendimiento rápido y confiable con virtualización nativa de Windows Hyper-V.
- Capacidad para trabajar de forma nativa en Linux a través de WSL 2 en máquinas Windows.
- Montaje de volumen para código y datos, incluidas notificaciones de cambio de archivo y fácil acceso a contenedores en ejecución en la red localhost.
- Desarrollo y depuración en contenedor con IDE compatibles.

#### **Instalar**

Instalar Docker Desktop desde la [página principal](https://docs.docker.com/docker-for-windows/install/) de Docker. Una vez instalado debe de abrir Docker Desktop, tal vez le pida reiniciar su computadora. Una vez en el Dashboard de Docker asegúrese que copiar el comando que aparece. Debe ser igual o parecido a este comando.

```shell
docker run -d -p 80:80 docker/getting-started
```

- **Antes de ejecutar este comando en la terminal** se debe asegurar en cual distribución de WSL esta.
Esto se puede observar en el *PowerShell* por el comando:

```shell
wsl -l
wsl -l -v
```

- Se podrá dar cuenta del estado de la distribución y la versión. Si de alguna forma la distribución que está usando está en la versión 1 debe cambiarlo. [Más Información](https://docs.docker.com/docker-for-windows/wsl/)

```shell
wsl.exe --set-version (nombre_de_la_distribución) 2
```

- Comando para que futuras instalaciones sean en la distribución 2:

```shell
wsl.exe --set-default-version 2
```

- Ahora puede ejecutar su *getting-started* de Docker.

<figure
class="video_container">
  <iframe 
  width="100%" height="315" src="https://www.youtube.com/embed/5RQbdMn04Oc" frameborder="0" allowfullscreen="true"> 
  </iframe>
</figure>

**Comment by xavier506** [comment]
I think reviewing docker, docker compose and describing why it is used and what needs to be done to install locally and run a project such as life bank is what we are looking for
