### ISSUE TITLE
Duplicated content - DevOps

### ISSUE THREAD

**Issue by leisterfrancisco** [eoscostarica/guide.eoscostarica.io#275]
Content is twice in the same section

**Don't forget to update the Spanish site too**

![image](https://user-images.githubusercontent.com/28828796/106171508-38ec6e80-6157-11eb-97b6-cd2eb6e7818b.png)

**Comment by Edgar097** [comment]
The Spanish site is already merge @leisterfrancisco

**Comment by Edgar097** [comment]
Those were the images that @xavier506 gave me, I don't know if they are ok

**Comment by xavier506** [comment]
Good Catch!

This is the correct image for CI

![CI_Example](https://user-images.githubusercontent.com/5632966/106228974-2f442480-61b2-11eb-9ceb-6d47ef5acb67.png)
