### ISSUE TITLE
Update Open Source Projects

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#289]
As a visitor to the site I should be able to see updated screenshots of the open source projects so that I am not presented with old information

https://guide.eoscostarica.io/docs/open-source-projects

**Comment by ldrojas** [comment]
@hanakoori01 can you please work on these screenshots of the following open-source projects?
- https://eosrate.io/
- https://eosio.online/
- https://lifebank.io/
- https://ggoods.io/

**Comment by xavier506** [comment]
- myvote eos dao

**Comment by xavier506** [comment]
- eden smart contracts

**Comment by xavier506** [comment]
- constancias municipales?
