### ISSUE TITLE
Update eosio dashboard images

### ISSUE THREAD

**Issue by leisterfrancisco** [eoscostarica/guide.eoscostarica.io#290]
Actualicemos la imagen que tenemos en la siguiente pagina por una mas nueva

https://guias.eoscostarica.io/docs/proyectos-de-codigo-abierto#tablero-de-red-de-eosio

https://mainnet.eosio.cr

**Comment by xavier506** [comment]
please check https://guias.eoscostarica.io/docs/proyectos-de-codigo-abierto/

![image](https://user-images.githubusercontent.com/5632966/106804459-06e17d80-662b-11eb-9414-c0db954fc517.png)
