### ISSUE TITLE
Improve Node Setup Tutorial - English

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#329]
https://guide.eoscostarica.io/docs/tutorials/node-installation

**Comment by JustinCast** [comment]
@xavier506 It is a producer node?

**Comment by JustinCast** [comment]
@xavier506 I'm seeing that the preexistent content is referring to Jungle Testnet. What if we setup a chain-agnostic producer node?

**Comment by JustinCast** [comment]
In case we want to setup a producer node pointing to Jungle testnet, there is a http://monitor.jungletestnet.io/#register register option for auto node installation
