### ISSUE TITLE
Improve OSS projects page UI & Screenshots

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#343]
Inconsistent format for different projects and outdated screenshots

https://guide.eoscostarica.io/docs/open-source-projects

what about using cards instead

- [ ] hacer lista de proyectos 
- [ ] actualizar layout (diseño)
- [ ] actulizar contenido

**Comment by xavier506** [comment]
- libre dao
 - local dev environments
 - proton affiliate 
 - tools
 - eden check 
 - boilerplates
 - etc

**Comment by hanakoori01** [comment]
## Propuesta de Categorías para la sección de [OSS projects](https://guide.eoscostarica.io/docs/open-source-projects)  

- Community Projects
- Tools 
- Boilerplates
- React Components
- Hackathons Projects
- NPM Packages 

@xavier506 ¿Qué opinas de esta estructura?

**Comment by hanakoori01** [comment]
## Proposal of organized content of open projects page 

- Community Projects
	- EOSIO Dashboard
	- EOS Rate
	- LACChain EOSIO Testnet
	- Evodex
	- EOS Foundation
- Tools
	- Digital Notary Smart Contract
	- Local Dev Environments
- Boilerplates
	- Projects
- React Components
- Hackathons
	- LifeBank
	- gGoods
- NPM Packages

@xavier506 @leisterfrancisco  What do you think of this structure?

**Comment by leisterfrancisco** [comment]
- Tools
  - https://proton.eosio.online/bpjson, [here is the code](https://github.com/eoscostarica/eoscr-components/tree/master/src/lib/BPJsonGenerator)
  - https://proton.eosio.online/nodes-distribution, [here is the code](https://github.com/eoscostarica/eosio-dashboard/tree/dev/webapp/src/components/GeoMap)

- Boilerplates [You can find them here](https://github.com/orgs/eoscostarica/repositories?q=boilerplate+&type=all&language=&sort=)

- React Components [Check our components here](https://components.eosio.cr/?path=/story/issuanceverifier--issuance-verifier-wrapper)

**Not sure** if `Digital Notary Smart Contract` belongs to `Tools`, in fact, I wouldn't list it, @xavier506 what do you think?
