### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by leisterfrancisco** [eoscostarica/guide.eoscostarica.io#347]
**Describe the bug**
Broken link in Readme file template.

**To Reproduce**
1. Go to https://guide.eoscostarica.io/docs/tools/readme-file-template/
2. Click on `click here`

![image](https://user-images.githubusercontent.com/28828796/115572365-101ed580-a27d-11eb-9c57-3ffd07fb6085.png)

**Comment by Mike3563** [comment]
- [ ] the broken link is fixed
