### ISSUE TITLE
Fix Broken links

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#359]
links to eosio documentation are broken 

https://guide.eoscostarica.io/docs/eos-learn/accounts-and-permissions/

**Comment by leisterfrancisco** [comment]
The link used in https://github.com/eoscostarica/guide.eoscostarica.io/pull/376 is not the latest, please use the latest link.

Change https://developers.eos.io/manuals/eosjs/v21.0/how-to-guides/how-to-create-an-account to https://developers.eos.io/manuals/eosjs/latest/how-to-guides/how-to-create-an-account
