### ISSUE TITLE
Wrong Language

### ISSUE THREAD

**Issue by leisterfrancisco** [eoscostarica/guide.eoscostarica.io#362]
**Describe the bug**
On english version there is a spanish text.

**To Reproduce**
1. Go to [Dapp Development](https://guide.eoscostarica.io/docs/eos-learn/dapp-development)
2. Scroll down to [Getting Started](https://guide.eoscostarica.io/docs/eos-learn/dapp-development/#getting-started)
3. See error

**Expected behavior**
English version.

**Screenshots**
<img width="1680" alt="Screen Shot 2021-12-06 at 15 53 32" src="https://user-images.githubusercontent.com/28828796/144928857-89d77d40-1ae2-4d94-a616-a84f84196d48.png">

**Comment by Mike3563** [comment]
- [ ] transcrip the line to english
