### ISSUE TITLE
Fix Broken video links

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#369]
Check all pages with videos for broken video links and fix or replace video if possible
for example:
![image](https://user-images.githubusercontent.com/5632966/148088733-70dad5a5-e612-4a99-842f-1210ff698965.png)

**Comment by hanakoori01** [comment]
Hello Xavier, 

The links are working nice but the problem is the video, it's probably removed from YouTube or something like that. 
Could you send me a new video link for this section so that I can replace the old one? 

 Thank you

**Comment by xavier506** [comment]
https://sistemasedenia.slack.com/archives/D02SBEVTYBY/p1641328747013000?thread_ts=1641327879.012500&channel=D02SBEVTYBY&message_ts=1641328747.013000


https://www.youtube.com/watch?v=E3Tx2DseLGE
