### ISSUE TITLE
Update Project dependencies

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#371]
Update all node dependencies

- [x] Update `package.json` docusarus version
- [x] Update `package.json` dependencies versions
- [x] Update `package.json` dependencies version to latest
- [x] test

**Comment by hanakoori01** [comment]
Hello Xavier, 

The version I committed in the last PR is the updated one, according to [Versioning](https://docusaurus.io/docs/versioning)

**Comment by xavier506** [comment]
**investigate using yarn for this :**
- `yarn outdated` lists outdated packages 
- `yarn upgrade` upgrades minor releases
- `yarn upgrade --latest` upgrades everything to latest version (breaking changes!!!!)
