### ISSUE TITLE
Improve infrastructure diagram

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#393]
The full. stack boilerplate diagrams can be improved and also updated across repos that use this template repo

![image](https://user-images.githubusercontent.com/5632966/148689926-513ea0ea-fe41-4a71-b7d0-2bfd3ca1621f.png)

**Comment by xavier506** [comment]
![infrastructure](https://user-images.githubusercontent.com/5632966/149192755-4448ec3f-fad8-4eae-86d1-30cb5f5287a4.png)

**Comment by fvives99** [comment]
- The newly updated diagram has been applied to the most recent readme located at the boilerplate repository and can be seen here: https://github.com/eoscostarica/full-stack-boilerplate

- This resolves issue 39: https://github.com/eoscostarica/full-stack-boilerplate/issues/39 at the Boilerplate repository.

- The Pull Request has been closed and merged and the changes have been applied successfully as seen in the image attached. 
![Screenshot from 2022-07-01 13-59-24](https://user-images.githubusercontent.com/55892352/176961351-b1c58654-d972-466f-97de-5c20e3eb584f.png)
