### ISSUE TITLE
Fix missing videos

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#400]
![image](https://user-images.githubusercontent.com/5632966/149018728-ee2ad9f6-d91d-42c3-bc8f-b0ba742b7c95.png)

**Comment by hanakoori01** [comment]
Hi Xavier,

The problem with this video is the same as the previous ones, the video is off YouTube or something like that. So what do you think about replacing it with this one? [Smart Contracts](https://www.youtube.com/watch?v=ZE2HxTmxfrI)

**Comment by xavier506** [comment]
yes lets replace it
