### ISSUE TITLE
Dark Mode Logos for Github

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#442]
### Logo images need to look well on dark mode and light mode

- for edenia and eoscostarica organizations
- must be the same image file for darkmode and light mode

![image](https://user-images.githubusercontent.com/104119005/178370231-eb301c93-5768-45ea-8647-6459637c1cf1.png)

![image](https://user-images.githubusercontent.com/5632966/178376026-0fa422a4-98c6-4134-883f-49f28b5f7b7b.png)

https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile

**Comment by Mike3563** [comment]
- [ ] create a repository english
- [ ] create a repository spanish
- [ ] poste on the organizacion profile

**Comment by xavier506** [comment]
@fvives99 Once we have the new images for both dark and light mode we should replace this in the project readme's across both organization's repos

**Comment by xavier506** [comment]
![EDENIA](https://user-images.githubusercontent.com/5632966/178800854-cffb01ea-b55a-44b2-bcfa-872301874a43.png)
![EOS](https://user-images.githubusercontent.com/5632966/178800859-e05a07ff-b3e5-41a9-9137-d1a271b958ff.png)

**Comment by fvives99** [comment]
Will add this image on the telos-local repo

![telosimage-2-585x292](https://user-images.githubusercontent.com/55892352/178833751-26f06df5-f330-4951-8441-68968c8b0ec8.png)

**Comment by fvives99** [comment]
will add also missing image
![wax-waxp-logo-C2E2CF0AA4-seeklogo com](https://user-images.githubusercontent.com/55892352/178836808-35b4aaee-db31-492e-b8cb-b0ddf5912186.png)
