### ISSUE TITLE
Optimize page links

### ISSUE THREAD

**Issue by Mike3563** [eoscostarica/guide.eoscostarica.io#465]
We have a problem with  react router because it is fails when backslash, in the guidelines. 
Check for errors or update to fix the problem 

Accentance Criteria:

- [ ] React Router do not fail when do a backslash
- [ ] Document why it happened.

**Comment by xavier506** [comment]
https://docusaurus.io/docs/api/docusaurus-config#trailingSlash @JAMares @warnerHurtado
