### ISSUE TITLE
Semantic Commit Messages

### ISSUE THREAD

**Issue by Mike3563** [eoscostarica/guide.eoscostarica.io#475]
As a developer I want to investigate and document the use of this tool and be able to apply it in a standardized way in the repositories.

you can use these links and repositories for information:

https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

https://www.conventionalcommits.org/en/v1.0.0/

Acceptante Criteria:

- [ ] Document English and Spanish
- [ ] Put it in the sidebar
- [ ] Write on markdown 
- [ ] Run spellcheck

**Comment by xavier506** [comment]
```
build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
ci: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
docs: Documentation only changes
feat: A new feature
fix: A bug fix
perf: A code change that improves performance
refactor: A code change that neither fixes a bug nor adds a feature
style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
test: Adding missing tests or correcting existing tests

```
