### ISSUE TITLE
EOSIO Networks

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#60]
Migrate content from latamlink article to a new page in the learning portal.
https://latamlink.io/docs/eosio-networks

Please be sure to omit any latamlink specific content so we only focus on general EOSIO topics.

**Comment by JeanVegaD** [comment]
@xavier506 

[This page](https://latamlink.io/docs/eosio-networks) has 2 broken links.

* [https://www.lynxwallet.io/](https://www.lynxwallet.io/)
* [ineos.io](https://ineos.io/)

should I put them?
