### ISSUE TITLE
Add medium articles to homepage

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/guide.eoscostarica.io#89]
- [Get to Know EOS Costa Rica](https://medium.com/@eoscostarica/get-to-know-eos-costa-rica-f91f5b0bb7c4)
- [What Is Blockchain? — An Introduction](https://medium.com/@eoscostarica/what-is-blockchain-an-introduction-9535ed3e6005)
- [You Should Participate in an Open-Source Project](https://medium.com/@eoscostarica/you-should-participate-in-an-open-source-project-c259f8759d41)
- [How to Choose an Enterprise Blockchain Platform?](https://medium.com/@eoscostarica/how-to-choose-an-enterprise-blockchain-platform-7c3665994ad6)

**Comment by murillojorge** [comment]
Aquí está el widget: 

`<div id="medium-widget"></div>
    <script src="https://medium-widget.pixelpoint.io/widget.js"></script>
    <script>MediumWidget.Init({renderTo: '#medium-widget', params: {"resource":"https://medium.com/@eoscostarica","postsPerLine":12,"limit":6,"picture":"big","fields":["description","claps","publishAt"],"ratio":"original"}})</script>
`
